### PR TITLE
chore(api): integrate blockscout search api

### PR DESCRIPTION
**Pull request by JoshuaC817**
#### What this PR does / why we need it:
as titled

#### Which issue(s) does this PR fixes?:

Fixes #

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*

### CODE REVIEW

**Review by lykalabrada — APPROVED** [review]
LGTM. Just a note to other devs that we're retaining the snake format format fields returned by the api (eg: `next_page_params`, `block_number`, etc.)

**Comment by lykalabrada** [comment]
image
@JoshuaC817 are you seeing this error too?

**Comment by JoshuaC817** [comment]
> image
> 
> @JoshuaC817 are you seeing this error too?

oh yes, checking on it now

**Review by pierregee — APPROVED** [review]

**Comment by JoshuaC817** [comment]
> image
> 
> @JoshuaC817 are you seeing this error too?

@pierregee @lykalabrada this should be fixed now

**Comment by JoshuaC817** [comment]
image
checking on another error

**Pull request merged**
